### ISSUE TITLE
Hardware not supported, despite building app to Nexus 6P

### ISSUE THREAD

**Issue by EgilSandfeld** [IndoorAtlas/unity-plugin#1]
Hi guys.

I get this error below when trying to build the example scene from the supplied unity example project to Android. I have added API key and secret to the IaBehavior.cs.

Removing indooratlas-android-sdk-2.5.2.aar from the Unity project stops this message from happening! So **the issues lie somewhere in the indooratlas-android-sdk-2.5.2.aar** package.

In build settings, I've tried setting Install Location to both External, Automatic and Force Internal. I have also tried changing "preferExternal" in supplied AndroidManifest in Plugins folder to "InternalOnly" and "Auto" - without luck either.

My phone is a Nexus 6P rooted, which I've previously used to map rooms in Map Creator 2.

![screenshot_20170925-135114](https://user-images.githubusercontent.com/5029330/30807085-b176ac5c-a1f8-11e7-84cf-40b98071808a.png)

**Comment by tejasGit0904** [comment]
Apparently the issue persists with note8 and indooratlas-android-sdk-2.6.1.aar as well.
