### ISSUE TITLE
Build Failed: Multiple dex files

### ISSUE THREAD

**Issue by momo-the-monster** [IndoorAtlas/unity-plugin#12]
Using Unity 2017.4.2f2, building the example scene using NDK r17, I get the following error when I try to build:

```
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_161\bin\java.exe -classpath "C:\Program Files\Unity2017.42f2\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lbitter/jnibridge/JNIBridge$a;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 19s
]
stdout[
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:prepareAndroidwrapperLibrary
:prepareIndooratlasAndroidSdk261Library
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:javaPreCompileRelease
:compileReleaseJavaWithJavac
:compileReleaseNdk NO-SOURCE
:compileReleaseSources
:lintVitalRelease
:mergeReleaseShaders
:compileReleaseShaders
:generateReleaseAssets
:mergeReleaseAssets
:transformClassesWithDexForRelease FAILED
19 actionable tasks: 19 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
```

**Comment by Yash0270** [comment]
Did you get a solution ??
Stuck with the same problem

**Comment by Yash0270** [comment]
@momo-the-monster  , can u help ?

**Comment by Yash0270** [comment]
@simomar  , can u help ?

**Comment by kndol** [comment]
I met a similar error:

> CommandInvokationFailure: Gradle build failed. 
> /Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/MacOS/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"
> 
> stderr[
> D8: Program type already present: bitter.jnibridge.JNIBridge
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/0.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/1.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/3.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/2.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/10.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/8.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/9.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/11.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/4.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/5.jar, /Users/KnDol/Documents/Unity/GO Map/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/6.jar
>   Program type already present: bitter.jnibridge.JNIBridge
>   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> ]
> stdout[
> :checkReleaseClasspath
> :preBuild UP-TO-DATE
> :preReleaseBuild UP-TO-DATE
> :compileReleaseAidl NO-SOURCE
> :compileReleaseRenderscript UP-TO-DATE
> :checkReleaseManifest UP-TO-DATE
> :generateReleaseBuildConfig UP-TO-DATE
> :prepareLintJar UP-TO-DATE
> :mainApkListPersistenceRelease UP-TO-DATE
> :generateReleaseResValues UP-TO-DATE
> :generateReleaseResources UP-TO-DATE
> :mergeReleaseResources UP-TO-DATE
> :createReleaseCompatibleScreenManifests UP-TO-DATE
> :processReleaseManifest
> :splitsDiscoveryTaskRelease UP-TO-DATE
> :processReleaseResources
> :generateReleaseSources
> :javaPreCompileRelease
> :compileReleaseJavaWithJavac
> :compileReleaseNdk NO-SOURCE
> :compileReleaseSources
> :lintVitalRelease
> :mergeReleaseShaders UP-TO-DATE
> :compileReleaseShaders UP-TO-DATE
> :generateReleaseAssets UP-TO-DATE
> :mergeReleaseAssets
> :transformClassesWithDexBuilderForRelease
> :transformDexArchiveWithExternalLibsDexMergerForRelease FAILED
> 21 actionable tasks: 9 executed, 12 up-to-date
> ]
> exit code: 1
> UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> Rethrow as GradleInvokationException: Gradle build failed
> UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
> UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()
> 

Does anybody have a solution for this error?

**Comment by kndol** [comment]
I copy the plugin folder only into asset folder, then I can success. Do not copy the androidwrapper folder.
