### ISSUE TITLE
[Android][IOS]WWW requests blocked

### ISSUE THREAD

**Issue by handrianj** [IndoorAtlas/unity-plugin#13]
Hi,

When using Indoor Atlas, it's impossible to communicate with a database since the WWW are not working. The call isn't made at all... Unity logs show no error.

Unity version 2017.3.0p2

Any workaround/fixes for that?

Thanks!

**Comment by human890209** [comment]
Hi, I see this Issue is closed. Did you find any workaround/fixes?
