### ISSUE TITLE
Can't find "artifacts dropdown" to extract indooratlas.unitypackage   

### ISSUE THREAD

**Issue by PallaviPandurangPawar** [IndoorAtlas/unity-plugin#19]
Hello 
I'm following your github link and step to use indooratlas in unity.
https://github.com/IndoorAtlas/unity-plugin

But not able to find artifacts dropdown menu to extract indooratlas.unitypackage.
Please Guide me how to do solve this issue.

**Comment by Cloudef** [comment]
It seems github has retention for the CI artifacts. I modified the repo to generate releases from tags, you can get the unitypackage from here now: https://github.com/IndoorAtlas/unity-plugin/releases/tag/0.0.3
