### ISSUE TITLE
Geofencing Not working 

### ISSUE THREAD

**Issue by BlacqShadow** [IndoorAtlas/unity-plugin#3]
when trying to add geofences to the plugin using function placeGeoFence() - called at the end of init : the error [IARegion boundingBox]: unrecognized selector sent to instance 0x1c4659140 pops up  
`- (void)placeGeofence
{
   
    NSMutableArray<NSNumber*> *edges = [NSMutableArray array];
    
    [edges addObject:[NSNumber numberWithDouble:-37.84811769]];
    [edges addObject:[NSNumber numberWithDouble:145.11430576]];
    [edges addObject:[NSNumber numberWithDouble:-37.84802129]];
    [edges addObject:[NSNumber numberWithDouble:145.11431266]];
    [edges addObject:[NSNumber numberWithDouble:-37.84792601]];
    [edges addObject:[NSNumber numberWithDouble:145.11432588]];
    [edges addObject:[NSNumber numberWithDouble:-37.84792520]];
    [edges addObject:[NSNumber numberWithDouble:145.11433971]];
    [edges addObject:[NSNumber numberWithDouble:-37.84802397]];
    [edges addObject:[NSNumber numberWithDouble:145.11433594]];
    [edges addObject:[NSNumber numberWithDouble:-37.84811399]];
    [edges addObject:[NSNumber numberWithDouble:145.11432856]];
    
    self.geofence = [IAPolygonGeofence polygonGeofenceWithIdentifier:@"Area 1" andFloor:nil edges:edges];

    [self.manager startMonitoringForGeofence:self.geofence];
    

}
`
The error occurs on the last line startMonitoringForGeofence

**Comment by Cloudef** [comment]
Check that your "self.geofence" property is set to "strong" instead of "copy".

**Comment by BlacqShadow** [comment]
Thanks, that was it, such a stupid mistake.
