### ISSUE TITLE
Add Path With Augmented reality, Need Z- coordinate

### ISSUE THREAD

**Issue by Devid2727** [IndoorAtlas/unity-plugin#5]
Hello Team

I am trying to create indoor navigation path with Augmented reality, I have used your example to start my work, In your example i have seen, you are getting  "X" and "Y" position, By using current latitude and longitude, But In case of Unity i need to render 3D object like arrow or simple line to show the paths or We can say road navigation, For this i need "Z" co-ordinate also. But your WGSConversion class i am getting only "deltaX" and "deltaY" values, How i can get "Z" axis value, I have refereed your below code. 

 ```
         const double a = 6378137.0;            // Earth's semimajor axis in meters in WGS84
		const double f = 1.0 / 298.257223563;  // Earth's flattening in WGS84
		const double b = a * (1.0 - f);
		const double a2 = a * a;
		const double b2 = b * b;
		double sinlat = System.Math.Sin(System.Math.PI / 180.0 * latitude);
		double coslat = System.Math.Cos(System.Math.PI / 180.0 * latitude);
		double tmp = System.Math.Sqrt(a2 * coslat * coslat + b2 * sinlat * sinlat);

		deltaX = (System.Math.PI / 180.0) * (a2 / tmp) * coslat;
		deltaY = (System.Math.PI / 180.0) * (a2 * b2 / (tmp * tmp * tmp)); 
```
I am trying to create Indoor navigation like below link 
[Sample Example Video](https://www.youtube.com/watch?v=A-rrkIlzEO8)

Could you please help me to fix this issues? or If i am on any wrong path, Please help me to get proper way to make such app with indoorAtlass.

**Comment by simomar** [comment]
Hi @Devid2727 

The linearisation you're referencing in the issue converts WGS coordinates (those (latitude, longitude) coordinates you receive from the location callbacks) to metric (East, North) coordinates. On top of this your "z value" should correspond to the altitude of the position fix.

You can get altitude from [Location's altitude field](https://github.com/IndoorAtlas/unity-plugin/blob/master/Plugins/Location.cs#L8). The altitude corresponds to the altitude of the floor plan. The floor plan altitude can be set in IndoorAtlas' webapp (select the floorplan -> edit floor plan info and image). The altitude can approximated from the floor level information if it isn't available.
With these components you can draw lines in (East, North, Up) coordinate system and implement your indoor navigation app.

I hope this helps.

**Comment by simomar** [comment]
I'm closing this issue. Feel free to open a new one if you face new problems using IndoorAtlas Unity plugin.
