### ISSUE TITLE
Your hardware does not support this application.

### ISSUE THREAD

**Issue by kansaraurmil55** [IndoorAtlas/unity-plugin#6]
I tried to run this project ( examplescene ) in my mobile (Samsung Note8) with everything (wifi, Bluetooth, GPS, Location service) enabled but still it is giving us problem "You hardware does not support this application.". I followed the step of copying plugins folder to assets folder and also provided api key and api secret key to the file IaBehaviour.cs still problem persists.

Can you please guide us where is the problem?

**Comment by simomar** [comment]
Hi

Sorry to hear. It seems we included native libraries which are not supported by Unity. Branch [fix/2.6.1-include-only-armv7-x86-libs](https://github.com/IndoorAtlas/unity-plugin/tree/fix/2.6.1-include-only-armv7-x86-libs) should fix the issue and I'll merge it soon.
