### ISSUE TITLE
Wayfinding

### ISSUE THREAD

**Issue by kansaraurmil55** [IndoorAtlas/unity-plugin#7]
I would like to know if there is any way we can have a cs file which gives us a list of points(latitude and longitude) to reach the destination.

Is there any file same as WayFinding in android and ios SDK examples?

It would be a great help.

Thanks.

**Comment by tejas0904** [comment]
Would like to know for the same issue if I can get hold of "'com.indooratlas.android:indooratlas-android-wayfinding:2.7.0-beta-9'" dependency which is in android same for unity?

**Comment by simomar** [comment]
We don't have short term plans to add wayfinding Unity wrappers.
If we decide to implement wayfinding support, it will be released in this repository.
